import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  documentationSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Global',
      link: {
        type: 'generated-index',
        title: 'Global Documentation',
        description: 'Essential documentation covering global rules, patterns, and configurations',
      },
      items: [
        {type: 'autogenerated', dirName: 'global'},
      ],
    },
    {
      type: 'category',
      label: 'Settings',
      link: {
        type: 'generated-index',
        title: 'Settings',
        description: 'Plugin settings pages and configuration options',
      },
      items: [
        {type: 'autogenerated', dirName: 'settings'},
      ],
    },
    {
      type: 'category',
      label: 'Reports',
      link: {
        type: 'generated-index',
        title: 'Report Pages',
        description: 'All report pages shown in the WP Statistics menu',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Visitor Insights',
          link: {
            type: 'generated-index',
            title: 'Visitor Insights Reports',
            description: 'Comprehensive visitor behavior and traffic analysis',
          },
          items: [
            {type: 'autogenerated', dirName: 'reports/visitor-insights'},
          ],
        },
        {
          type: 'category',
          label: 'Page Insights',
          link: {
            type: 'generated-index',
            title: 'Page Insights Reports',
            description: 'Page-level content performance',
          },
          items: [
            {type: 'autogenerated', dirName: 'reports/page-insights'},
          ],
        },
        {
          type: 'category',
          label: 'Referrals',
          link: {
            type: 'generated-index',
            title: 'Referrals Reports',
            description: 'Traffic source and referral analysis',
          },
          items: [
            {type: 'autogenerated', dirName: 'reports/referrals'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Widgets',
      link: {
        type: 'generated-index',
        title: 'Reusable Widgets',
        description: 'Reusable widgets used across multiple report pages',
      },
      items: [
        {type: 'autogenerated', dirName: 'widgets'},
      ],
    },
    {
      type: 'category',
      label: 'Components',
      link: {
        type: 'generated-index',
        title: 'Base UI Components',
        description: 'Base UI components that power the widgets',
      },
      items: [
        {type: 'autogenerated', dirName: 'components'},
      ],
    },
    {
      type: 'category',
      label: 'Columns',
      link: {
        type: 'generated-index',
        title: 'Table Columns',
        description: 'Reusable table column definitions used across data table widgets',
      },
      items: [
        {type: 'autogenerated', dirName: 'columns'},
      ],
    },
    {
      type: 'category',
      label: 'Definitions',
      link: {
        type: 'generated-index',
        title: 'Glossary',
        description: 'Internal glossary of analytics terms, metrics, and concepts used in WP Statistics',
      },
      items: [
        {type: 'autogenerated', dirName: 'definitions'},
      ],
    },
    {
      type: 'category',
      label: 'Technical',
      link: {
        type: 'generated-index',
        title: 'Technical Documentation',
        description: 'Technical documentation including database schema, API specifications, system architecture, and data flow',
      },
      items: [
        {type: 'autogenerated', dirName: 'technical'},
      ],
    },
  ],
};

export default sidebars;
