import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  documentationSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Global',
      link: {
        type: 'generated-index',
        title: 'Global Documentation',
        description: 'Essential documentation covering global rules, patterns, and configurations',
      },
      items: [
        {type: 'autogenerated', dirName: 'global'},
      ],
    },
    {
      type: 'category',
      label: 'Settings',
      link: {
        type: 'generated-index',
        title: 'Settings',
        description: 'Plugin settings pages and configuration options',
      },
      items: [
        {type: 'autogenerated', dirName: 'settings'},
      ],
    },
    {
      type: 'category',
      label: 'Reports',
      link: {
        type: 'generated-index',
        title: 'Report Pages',
        description: 'All report pages shown in the WP Statistics menu',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Visitor Insights',
          link: {
            type: 'generated-index',
            title: 'Visitor Insights Reports',
            description: 'Comprehensive visitor behavior and traffic analysis',
          },
          items: [
            {type: 'autogenerated', dirName: 'reports/visitor-insights'},
          ],
        },
        {
          type: 'category',
          label: 'Geographic',
          link: {
            type: 'generated-index',
            title: 'Geographic Reports',
            description: 'Location-based visitor analysis by country, city, and region',
          },
          items: [
            {type: 'autogenerated', dirName: 'reports/geographic'},
          ],
        },
        {
          type: 'category',
          label: 'Page Insights',
          link: {
            type: 'generated-index',
            title: 'Page Insights Reports',
            description: 'Page-level content performance',
          },
          items: [
            {type: 'autogenerated', dirName: 'reports/page-insights'},
          ],
        },
        {
          type: 'category',
          label: 'Referrals',
          link: {
            type: 'generated-index',
            title: 'Referrals Reports',
            description: 'Traffic source and referral analysis',
          },
          items: [
            {type: 'autogenerated', dirName: 'reports/referrals'},
          ],
        },
        {
          type: 'category',
          label: 'Content Analytics',
          link: {
            type: 'generated-index',
            title: 'Content Analytics Reports',
            description: 'Content performance by post type, author, and taxonomy',
          },
          items: [
            {type: 'autogenerated', dirName: 'reports/content-analytics'},
          ],
        },
        {
          type: 'category',
          label: 'Devices',
          link: {
            type: 'generated-index',
            title: 'Devices Reports',
            description: 'Device, browser, and operating system analysis',
          },
          items: [
            {type: 'autogenerated', dirName: 'reports/devices'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Widgets',
      link: {
        type: 'generated-index',
        title: 'Reusable Widgets',
        description: 'Reusable widgets used across multiple report pages',
      },
      items: [
        {type: 'autogenerated', dirName: 'widgets'},
      ],
    },
    {
      type: 'category',
      label: 'Components',
      link: {
        type: 'generated-index',
        title: 'Base UI Components',
        description: 'Base UI components that power the widgets',
      },
      items: [
        {type: 'autogenerated', dirName: 'components'},
      ],
    },
    {
      type: 'category',
      label: 'Columns',
      link: {
        type: 'generated-index',
        title: 'Table Columns',
        description: 'Reusable table column definitions used across data table widgets',
      },
      items: [
        {type: 'autogenerated', dirName: 'columns'},
      ],
    },
    {
      type: 'category',
      label: 'Definitions',
      link: {
        type: 'generated-index',
        title: 'Glossary',
        description: 'Internal glossary of analytics terms, metrics, and concepts used in WP Statistics',
      },
      items: [
        {type: 'autogenerated', dirName: 'definitions'},
      ],
    },
    {
      type: 'category',
      label: 'Technical',
      link: {
        type: 'generated-index',
        title: 'Technical Documentation',
        description: 'Technical documentation including database schema, API specifications, system architecture, and data flow',
      },
      items: [
        'technical/intro',
        {
          type: 'category',
          label: 'Frontend',
          link: {
            type: 'generated-index',
            title: 'Frontend Documentation',
            description: 'React component documentation, UI patterns, and frontend development guidelines',
          },
          items: [
            'technical/frontend/intro',
            {
              type: 'category',
              label: 'UI Components',
              link: {
                type: 'generated-index',
                title: 'UI Components',
                description: 'Base UI component library built on Radix UI and shadcn/ui',
              },
              items: [
                {type: 'autogenerated', dirName: 'technical/frontend/ui'},
              ],
            },
            {
              type: 'category',
              label: 'Custom Components',
              link: {
                type: 'generated-index',
                title: 'Custom Components',
                description: 'WP Statistics domain-specific components built with UI components',
              },
              items: [
                {type: 'autogenerated', dirName: 'technical/frontend/custom'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'API',
          link: {
            type: 'generated-index',
            title: 'API Documentation',
            description: 'REST API and Admin-Ajax endpoints for fetching analytics data',
          },
          items: [
            {type: 'autogenerated', dirName: 'technical/api'},
            {
              type: 'category',
              label: 'Localize Data',
              link: {
                type: 'generated-index',
                title: 'Localize Data',
                description: 'Initial configuration and data provided to the dashboard via WordPress localize script',
                slug: '/technical/api/localize-data',
              },
              items: [
                {
                  type: 'doc',
                  id: 'technical/localize-data/overview',
                  label: 'Overview',
                },
                {
                  type: 'doc',
                  id: 'technical/localize-data/globals',
                  label: 'Globals Data',
                },
                {
                  type: 'doc',
                  id: 'technical/localize-data/filters',
                  label: 'Filters Data',
                },
                {
                  type: 'doc',
                  id: 'technical/localize-data/layout',
                  label: 'Layout Data',
                },
                {
                  type: 'doc',
                  id: 'technical/localize-data/header',
                  label: 'Header Data',
                },
              ],
            },
            {
              type: 'doc',
              id: 'technical/api-endpoints/get-filter-options',
              label: 'Get Filter Options',
            },
            {
              type: 'doc',
              id: 'technical/api-endpoints/analytics-query-api',
              label: 'Analytics Query API',
            },
            {
              type: 'doc',
              id: 'technical/api-endpoints/user-preferences',
              label: 'User Preferences',
            },
          ],
        },
        {
          type: 'category',
          label: 'Architecture',
          link: {
            type: 'generated-index',
            title: 'System Architecture',
            description: 'Backend and frontend architecture, query building, and integration patterns',
          },
          items: [
            {type: 'autogenerated', dirName: 'technical/architecture'},
          ],
        },
        {
          type: 'category',
          label: 'Database',
          link: {
            type: 'generated-index',
            title: 'Database Schema',
            description: 'Database tables, relationships, and data storage structure',
          },
          items: [
            {type: 'autogenerated', dirName: 'technical/database'},
          ],
        },
        {
          type: 'doc',
          id: 'technical/testing/unit-testing',
          label: 'Testing',
        },
      ],
    },
  ],
};

export default sidebars;
